### PR TITLE
feat: [cheqd] bump cheqd-node to 1.3.0 for mainnet chain (#105)

### PR DESCRIPTION
**Pull request by lampkin-diet**
## Description

Closes: #XXXX

It bumps cheqd-node version to 1.3.0 and makes forbole/bdjuno in sync with changes in our fork.
Changes:
- bump pacakges
- add MsgDeactivateDidDoc support

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [x] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MonikaCat** [comment]
Hi @anikitinDSR can you also add entry inside the `CHANGELOG.md` pls? Thanks

**Review by rmontagnin — APPROVED** [review]

**Comment by lampkin-diet** [comment]
Hey, @MonikaCat and @RiccardoM ! Are there any actions from my side which I need to do for make it passed?

**Comment by rmontagnin** [comment]
@anikitinDSR Try running `make test-unit` on your PC and see if tests passes. I think they need to be changed, or there is something wrong with the code if they are not passing on our CI

**Comment by lampkin-diet** [comment]
> @anikitinDSR Try running `make test-unit` on your PC and see if tests passes. I think they need to be changed, or there is something wrong with the code if they are not passing on our CI

Hey! I ran the tests locally even for my last commit and for `fc756efd1507989cf450a37bbf1b7a19c2cc9e10` (it was the state right before my changes) and result is the same. It fails on test:
```
=== RUN   TestDatabaseTestSuite/TestBigDipperDb_SaveInflation
    /Users/anikitin/projects/cheqd/bdjuno/database/mint_test.go:27:
        	Error Trace:	/Users/anikitin/projects/cheqd/bdjuno/database/mint_test.go:27
        	Error:      	Should be true
        	Test:       	TestDatabaseTestSuite/TestBigDipperDb_SaveInflation
```
Could you @MonikaCat  or @RiccardoM take a look at the tests? Maybe at least check, that before my changes everything worked fine?

**Comment by MonikaCat** [comment]
Hey @anikitinDSR can you merge the latest changes from [chains/cheqd/mainnet](https://github.com/forbole/bdjuno/tree/chains/cheqd/mainnet) ? I think it should fix the error

**Review by MonikaCat — APPROVED** [review]

**Pull request merged**
