### PR TITLE
feat: [likecoin] support likechain dual prefix (merged v3.1.0-stargate)

### PR DESCRIPTION
**Pull request by huichiaotsou**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [x] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MonikaCat** [comment]
_Note: Unit-tests are failing due to dual prefix_

**Comment by MonikaCat** [comment]
@huichiaotsou can you also update `CHANGELOG.md` pls?

**Review by MonikaCat — APPROVED** [review]
tested, LGTM

**Comment by rmontagnin** [comment]
Some tests are failing, can you fix them?

**Comment by huichiaotsou** [comment]
> Some tests are failing, can you fix them?

Hi @RiccardoM, tests failures are basically caused by the address prefixes(likecoin dual-prefix). I was thinking if the main branch has past the tests then we can omit the tests here?

**Comment by rmontagnin** [comment]
> Hi @RiccardoM, tests failures are basically caused by the address prefixes(likecoin dual-prefix). I was thinking if the main branch has past the tests then we can omit the tests here?

We should really *not* merge anything that has failing tests. Any way we can fix the tests to make them pass? If they are failing it means that most likely things will break in production. So either the new code is not correct, or we need to change something

**Review by MonikaCat — CHANGES_REQUESTED** [review]
[This part](https://github.com/forbole/bdjuno/blob/34d517138952ff5fb9a01e5069b7a5ad0fc68342/database/staking_validators.go#L402) is throwing an error ` pq: ON CONFLICT DO UPDATE command cannot affect row a second time` when storing validators voting power, can you update it pls?

**Comment by huichiaotsou** [comment]
> [This part](https://github.com/forbole/bdjuno/blob/34d517138952ff5fb9a01e5069b7a5ad0fc68342/database/staking_validators.go#L402) is throwing an error ` pq: ON CONFLICT DO UPDATE command cannot affect row a second time` when storing validators voting power, can you update it pls?

hi @MonikaCat the error is about bdjuno tries to insert 2 addresses of like and cosmos prefixes to a single validator. I clear up my DB and start parsing from block 1 and it did not throw this error. 

but indeed I have just updated the `GetValidatorsVotingPowers` method which needed to be updated

**Comment by MonikaCat** [comment]
tested, LGTM

**Review by MonikaCat — APPROVED** [review]

**Review by rmontagnin — APPROVED** [review]
utACK

**Pull request merged**
