### PR TITLE
[e-Money] fix: gas prices not being updated periodically

### LINKED ISSUE #202: [e-Money] Get minimum gas prices
## Feature description 

Log the minimum gas prices from x/authority

```
emd q authority gas-prices
```

```
{
  "min_gas_prices": [
    {
      "denom": "echf",
      "amount": "0.530000000000000000"
    },
    {
      "denom": "edkk",
      "amount": "3.700000000000000000"
    },
    {
      "denom": "eeur",
      "amount": "0.500000000000000000"
    },
    {
      "denom": "enok",
      "amount": "6.100000000000000000"
    },
    {
      "denom": "esek",
      "amount": "5.500000000000000000"
    },
    {
      "denom": "ungm",
      "amount": "1.000000000000000000"
    }
  ]
}
```

### LINKED ISSUE #213: [e-Money] Gas prices periodic ops not working without genesis parsed
## Bug description

the periodic operations handler for gas prices is currently not working because it only handles UPDATE the table on gas_prices & height columns, whereas the genesis being not parsed, the initial row is not there so the UPDATE will fail. 

## Expected behavior

Checked with Wingman that they won't need the authority_key, planning to remove the column from the table, leaving only gas_prices and height

### PR DESCRIPTION
**Pull request by huichiaotsou**
## Description
Fixes #213, closes #202 

## Checklist
- [x] Targeted PR against correct branch.
- [x] Linked to Github issue with discussion and accepted design OR link to spec that describes this work.
- [x] Wrote unit tests.  
- [x] Re-reviewed `Files changed` in the Github PR explorer.

### CODE REVIEW

**Comment by huichiaotsou** [comment]
hello @MonikaCat, this morning I realized that my periodic operations handler for gas prices would not work because it [only handles UPDATE table](https://github.com/forbole/bdjuno/blob/chains/emoney/mainnet/database/emoney_authority.go#L32)(**authority_key** can only be obtained from the genesis, so the periodic operations could only use UPDATE). However there is no row to be UPDATEd because genesis was not parsed... the UPDATE then will fall in error. 

So I discussed with @ryuash and she confirmed that they won't need the **authority_key** so I removed it from the type struct as well as from the table. Now handle_genesis and handle_periodic_operations both use INSERT INTO ON CONFLICT so it will prevent the error.

**Comment by rmontagnin** [comment]
@huichiaotsou Can we leave the `authority_key` field and still use the `one_row_id`? I think other people might want to have that data (i.e. if they are customizing BigDipper). 

Also, will this close #202 as well? If so, can you add it to the description please?

**Comment by huichiaotsou** [comment]
> @huichiaotsou Can we leave the `authority_key` field and still use the `one_row_id`? I think other people might want to have that data (i.e. if they are customizing BigDipper).
> 
Sure, I will add this col in the table and still include insert of this data from handle_genesis 
as for PeriodicOperations I will then leave authority_key un-updated.

> Also, will this close #202 as well? If so, can you add it to the description please?
>
OK added!

**Comment by rmontagnin** [comment]
> Sure, I will add this col in the table and still include insert of this data from handle_genesis as for PeriodicOperations I will then leave authority_key un-updated.

Hmm not sure I quite understand then. Isn't this key retrieved from the querier that gets the gas prices? If not then we can leave it out. I thought that is was returned by the querier cause it would have made sense to indicate who was the last one updating the prices

**Comment by huichiaotsou** [comment]
> > Sure, I will add this col in the table and still include insert of this data from handle_genesis as for PeriodicOperations I will then leave authority_key un-updated.
> 
> Hmm not sure I quite understand then. Isn't this key retrieved from the querier that gets the gas prices? If not then we can leave it out. I thought that is was returned by the querier cause it would have made sense to indicate who was the last one updating the prices

😆  no, the query only returns gas prices but no authority key

**Comment by rmontagnin** [comment]
> laughing no, the query only returns gas prices but no authority key

Ok then we can leave it as it is. If the work has done, you can mark this PR as "Ready for review" :smile:

**Comment by huichiaotsou** [comment]
> > laughing no, the query only returns gas prices but no authority key
> 
> Ok then we can leave it as it is. If the work has done, you can mark this PR as "Ready for review" 😄

perfect ! just switched

**Pull request merged**
