### PR TITLE
fix: replace GetHeightRequestHeader with GetHeightRequestContext

### PR DESCRIPTION
**Pull request by huichiaotsou**
## Description

Closes: #XXXX

code update after [juno PR](https://github.com/forbole/juno/pull/40) merged

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [x] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Review by MonikaCat — DISMISSED** [review]
N/A

**Comment by MonikaCat** [comment]
@huichiaotsou I tested it locally with desmos chain and I find that bdjuno throws this error and doesn't store pool value in db: 
`error while getting staking pool: rpc error: code = Internal desc = UnmarshalJSON cannot decode empty bytes`  
Can you check it pls?

**Comment by huichiaotsou** [comment]
> @huichiaotsou I tested it locally with desmos chain and I find that bdjuno throws this error and doesn't store pool value in db: `error while getting staking pool: rpc error: code = Internal desc = UnmarshalJSON cannot decode empty bytes` Can you check it pls?

Hi @MonikaCat , could it be that the height is not enough to get the pool? I got error locally when the height is below 100 but If I run on a remote desmos node from height 2,060,000 I will not get the error and the value is stored: 

Screen Shot 2022-01-27 at 11 11 50 AM

**Comment by MonikaCat** [comment]
@huichiaotsou Ok I tested it again, its working 👍🏻

**Review by MonikaCat — APPROVED** [review]
Tested, LGTM

**Review by rmontagnin — APPROVED** [review]
utACK

**Pull request merged**
