### PR TITLE
feat: [certik] apply certik's custom gov types (proposal, deposit params, and tally params)

### PR DESCRIPTION
**Pull request by huichiaotsou**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [x] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MonikaCat** [comment]
The proposer address is never stored in database when parsing genesis file. I think we need to update [this line](https://github.com/forbole/bdjuno/blob/b8ae3ece23369adb36fa2e793f610bf236cd4e64/modules/gov/handle_genesis.go#L65) and pass `proposal.Proposer` value instead of an empty string

**Comment by huichiaotsou** [comment]
> The proposer address is never stored in database when parsing genesis file. I think we need to update [this line](https://github.com/forbole/bdjuno/blob/b8ae3ece23369adb36fa2e793f610bf236cd4e64/modules/gov/handle_genesis.go#L65) and pass `proposal.Proposer` value instead of an empty string

Hi @MonikaCat it's done :D

**Review by MonikaCat — APPROVED** [review]
LGTM

**Comment by huichiaotsou** [comment]
closed as merged in #418,

**Pull request closed without merging**
