### PR TITLE
feat: [cheqd] update cheqd-node to `1.4.0`

### PR DESCRIPTION
**Pull request by lampkin-diet**
## Description

Closes: #XXXX

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [ ] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [ ] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [ ] reviewed "Files changed" and left comments if necessary
- [ ] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MonikaCat** [comment]
Hey @anikitinDSR can you also update `CHANGELOG.md` pls? Thx!

**Comment by lampkin-diet** [comment]
> 

Hey! Sorry for late answer, just made needed changes

**Comment by MonikaCat** [comment]
Hey @anikitinDSR thanks for that, could you also run `golangci-lint run` to fix the lint error pls? Thanks!

**Comment by lampkin-diet** [comment]
> Hey @anikitinDSR thanks for that, could you also run `golangci-lint run` to fix the lint error pls? Thanks!

Have you changed something in linting for golang? Cause I've not made changes for go files. Also, BTW other PRs from dependabot also fails because of lint. Maybe they are connected with it? Or maybe you bumped golangci-lint?

**Review by MonikaCat — APPROVED** [review]

**Pull request merged**
