### PR TITLE
fix: BondedTokens exceeds int64 range

### PR DESCRIPTION
**Pull request by huichiaotsou**
## Description

Closes: #XXXX

fix bonded tokens / unbonded tokens exceeding range with int64. 
Store the value as string instead. 

---

### Author Checklist

*All items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow up issues.*

I have...

- [x] included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] added `!` to the type prefix if API or client breaking change
- [x] targeted the correct branch
- [ ] provided a link to the relevant issue or specification
- [ ] added a changelog entry to `CHANGELOG.md`
- [ ] included comments for [documenting Go code](https://blog.golang.org/godoc)
- [ ] updated the relevant documentation or specification
- [x] reviewed "Files changed" and left comments if necessary
- [x] confirmed all CI checks have passed

### Reviewers Checklist

*All items are required. Please add a note if the item is not applicable and please add
your handle next to the items reviewed if you only reviewed selected items.*

I have...

- [ ] confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ] confirmed `!` in the type prefix if API or client breaking change
- [ ] confirmed all author checklist items have been addressed
- [ ] reviewed API design and naming
- [ ] reviewed documentation is accurate
- [ ] reviewed tests and test coverage
- [ ] manually tested (if applicable)

### CODE REVIEW

**Comment by MonikaCat** [comment]
@huichiaotsou Can you also update the schema for `proposal_staking_pool_snapshot` table ?

**Comment by huichiaotsou** [comment]
> @huichiaotsou Can you also update the schema for `proposal_staking_pool_snapshot` table ?

Hi hi @MonikaCat I found out that the type we use [in staking_pool table](https://github.com/forbole/bdjuno/blob/6f29ed82b677bc45a5093e831271fbe02fd66879/database/schema/03-staking.sql#L17) is also BIGINT, should I update both or we can keep BIGINT for both tables?

**Comment by MonikaCat** [comment]
@huichiaotsou Yes let's update the `staking_pool` table to TEXT type as well, coz on some chains this value might also be too large to store as a BIGINT

**Review by MonikaCat — APPROVED** [review]
LGTM

**Review by rmontagnin — APPROVED** [review]
utACK

**Pull request merged**
